# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build date-processor

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java_version: ['1.8', '11', '15']

    name: Run tests under Java ${{matrix.java_version}}
    runs-on: ubuntu-latest

    steps:
    - uses: axibase/checkout@v2
    - name: Cache local Maven repository
      uses: axibase/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK for Java ${{matrix.java_version}}
      uses: axibase/setup-java@v1
      with:
        java-version: ${{matrix.java_version}}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Ptesting
